import os
from dotenv import load_dotenv

load_dotenv()

# BROKER
ZERODHA_API_KEY = os.getenv("ZERODHA_API_KEY")
ZERODHA_API_SECRET = os.getenv("ZERODHA_API_SECRET")
ZERODHA_USER_ID = os.getenv("ZERODHA_USER_ID")

# ANTHROPIC
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")

# CAPITAL
TOTAL_CAPITAL = 750000  # Rs 7,50,000 midpoint of target range
ACTIVE_TRADING_CAPITAL = 300000  # Rs 3,00,000 deployed as margin
RESERVE_BUFFER = 250000  # Never deployed in normal conditions
COIN_FUND_CAPITAL = 150000  # Always parked in liquid fund
CASH_BUFFER = 50000  # For brokerage and settlement

# INSTRUMENTS
NIFTY_LOT_SIZE = 25
BANKNIFTY_LOT_SIZE = 15
PRIMARY_INSTRUMENT = "NIFTY"
NIFTY_INSTRUMENT_TOKEN = 256265  # Kite Connect instrument token for NIFTY 50

# IRON CONDOR PARAMETERS
IC_SHORT_DELTA = 0.16
IC_WING_WIDTH_POINTS = 500
IC_MIN_DTE_ENTRY = 30
IC_MAX_DTE_ENTRY = 45
IC_MIN_IV_RANK = 30
IC_PROFIT_TARGET_PCT = 0.50
IC_STOP_LOSS_MULTIPLIER = 2.0
IC_TIME_STOP_DTE = 21
IC_MAX_OPEN_POSITIONS = 2
IC_MAX_PCT_CAPITAL_PER_TRADE = 0.05

# CALENDAR SPREAD PARAMETERS
# Nifty weekly expiries were discontinued by NSE in late 2024.
# Front month uses the nearest MONTHLY expiry (~20-30 DTE) instead of weeklies.
CAL_BACK_MONTH_MIN_DTE = 60
CAL_BACK_MONTH_MAX_DTE = 75
CAL_FRONT_MONTH_MIN_DTE = 20  # Nearest monthly expiry (was 7 for weeklies)
CAL_FRONT_MONTH_MAX_DTE = 35  # Upper bound for front month selection
CAL_PROFIT_TARGET_PCT = 0.50
CAL_BACK_MONTH_CLOSE_DTE = 25
CAL_MAX_MOVE_PCT_TO_ADJUST = 0.02
CAL_MAX_MOVE_PCT_TO_CLOSE = 0.04
CAL_MAX_OPEN_POSITIONS = 2

# RISK CONTROLS
VIX_MAX_FOR_IC = 25
VIX_HIGH_THRESHOLD = 28
ACCOUNT_DRAWDOWN_SIZE_DOWN = 0.03
ACCOUNT_DRAWDOWN_STOP = 0.05
ROLLING_WIN_RATE_YELLOW = 0.62
ROLLING_WIN_RATE_RED = 0.58
PROFIT_FACTOR_YELLOW = 1.1
PROFIT_FACTOR_RED = 1.0

# COSTS (Updated to FY 2024-25 rates)
COST_BROKERAGE_PER_ORDER = 20
COST_BROKERAGE_GST_RATE = 0.18
COST_STT_SELL_RATE = 0.000625  # 0.0625% on sell side (Budget 2024)
COST_STT_ITM_EXPIRY_RATE = 0.00125  # 0.125% of intrinsic value on ITM expiry
COST_NSE_EXCHANGE_RATE = 0.00053  # NSE F&O transaction charge
COST_SEBI_FEE_RATE = 0.000001  # Rs 10 per crore = 0.0001%
COST_STAMP_DUTY_RATE = 0.00003  # 0.003% on buy side
COST_SLIPPAGE_PER_UNIT_PER_LEG = 2
COST_LIQUID_FUND_RATE_ANNUAL = 0.065

# TELEGRAM ALERTS (primary notification channel)
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

# SYSTEM
DATABASE_URL = "sqlite:///./quant_system.db"
DATABASE_WAL_MODE = True
TIMEZONE = "Asia/Kolkata"
MARKET_OPEN = "09:15"
MARKET_CLOSE = "15:30"
DATA_REFRESH_INTERVAL_MIN = 15
POSITION_POLL_INTERVAL_SEC = 60
